cake.config
setup.cake
tools/packages.config

Update to Cake 0.23.0 for compatibility with latest Cake.Recipe
Fixes #10

(GH-10) Upgrade to Cake 0.23.0

---

src/Cake.Issues.PullRequests.Tests/Cake.Issues.PullRequests.Tests.csproj
src/Cake.Issues.PullRequests.Tests/FakePullRequestSystem.cs
src/Cake.Issues.PullRequests.Tests/IPullRequestSystemExtensionTests.cs
src/Cake.Issues.PullRequests.Tests/OrchestratorTests.cs
src/Cake.Issues.PullRequests/Cake.Issues.PullRequests.csproj
src/Cake.Issues.PullRequests/IPullRequestSystem.cs
src/Cake.Issues.PullRequests/IPullRequestSystemExtension.cs
src/Cake.Issues.PullRequests/Orchestrator.cs
src/Cake.Issues.PullRequests/PullRequestSystem.cs
src/Cake.Issues.PullRequests/ReportIssuesToPullRequestSettings.cs

Check if commit ID for which issues were reported is outdated
Fixes #2

(GH-2) Check if commit ID for which issues were reported is outdated

---

src/Cake.Issues.PullRequests.Tests/Cake.Issues.PullRequests.Tests.csproj
src/Cake.Issues.PullRequests.Tests/IssueFiltererTests.cs
src/Cake.Issues.PullRequests.Tests/OrchestratorTests.cs
src/Cake.Issues.PullRequests/Cake.Issues.PullRequests.csproj

Update to Cake.Issues 0.3.0-beta.1
Fixes #20

(GH-20) Update to Cake.Issues 0.3.0-beta.1

---

src/Cake.Issues.PullRequests/ReportIssuesToPullRequestSettings.cs

Fix typo in comment

---

tools/packages.config

Build with Cake 0.29.0
Fixes #32

(GH-32) Build with Cake 0.29.0

---

src/Cake.Issues.PullRequests.Tests/Cake.Issues.PullRequests.Tests.csproj
src/Cake.Issues.PullRequests.Tests/FakePullRequestSystem.cs
src/Cake.Issues.PullRequests/Cake.Issues.PullRequests.csproj
src/Cake.Issues.PullRequests/IPullRequestSystem.cs
src/Cake.Issues.PullRequests/PullRequestSystem.cs

Update StyleCop to latest beta version to get support for recent C# versions

Update StyleCop to latest beta version

---

src/Cake.Issues.PullRequests.Tests.ruleset
src/Cake.Issues.PullRequests.Tests/IPullRequestSystemExtensionTests.cs
src/Cake.Issues.PullRequests.Tests/IssueFiltererTests.cs
src/Cake.Issues.PullRequests.Tests/OrchestratorTests.cs
src/Cake.Issues.PullRequests.Tests/PullRequestDiscussionThreadTests.cs
src/Cake.Issues.PullRequests.Tests/PullRequestIssueResultTests.cs
src/Cake.Issues.PullRequests.Tests/PullRequestSystemTests.cs
src/Cake.Issues.PullRequests.Tests/PullRequestsFixture.cs
src/Cake.Issues.PullRequests.Tests/ReportIssuesToPullRequestSettingsTests.cs
src/Cake.Issues.PullRequests.ruleset
src/Cake.Issues.PullRequests.sln.DotSettings
src/Cake.Issues.PullRequests/Aliases.cs
src/Cake.Issues.PullRequests/IPullRequestDiscussionThread.cs
src/Cake.Issues.PullRequests/IssueFilterer.cs
src/Cake.Issues.PullRequests/Orchestrator.cs
src/Cake.Issues.PullRequests/PullRequestDiscussionThread.cs
src/Cake.Issues.PullRequests/ReportIssuesToPullRequestSettings.cs

Fix code analysis issues

---

src/Cake.Issues.PullRequests.Tests/Cake.Issues.PullRequests.Tests.csproj
src/Cake.Issues.PullRequests/Cake.Issues.PullRequests.csproj

Update to Cake.Issues 0.4.0
Fixes #39

(GH-39) Update to Cake.Issues 0.4.0

---

src/Cake.Issues.PullRequests.Tests/OrchestratorTests.cs
src/Cake.Issues.PullRequests/Orchestrator.cs

Only resolve and reopen comments from the same comment source 
Fixes #36

 (GH-36) Only resolve and reopen comments from the same comment source 

---

src/Cake.Issues.PullRequests.Tests/OrchestratorTests.cs

Improve tests
Requires #36 to be merged first

Improve tests

---

src/Cake.Issues.PullRequests.Tests/Cake.Issues.PullRequests.Tests.csproj
src/Cake.Issues.PullRequests/Cake.Issues.PullRequests.csproj

Update to Cake.Issues 0.5.0-beta.2
Fixes #41

(GH-41) Update to Cake.Issues 0.5.0

---

src/Cake.Issues.PullRequests.Tests/OrchestratorTests.cs
src/Cake.Issues.PullRequests.Tests/PullRequestsFixture.cs
src/Cake.Issues.PullRequests/Aliases.cs
src/Cake.Issues.PullRequests/IssueFilterer.cs
src/Cake.Issues.PullRequests/Orchestrator.cs

Add alias which accepts a list of issues.
Fixes #28

(GH-28) Add alias which accepts list of issues

---

nuspec/nuget/Cake.Issues.PullRequests.nuspec

Use jsDelivr for icon since RawGit is shutting down

Use jsDelivr for icon

---

src/Cake.Issues.PullRequests/Aliases.cs

Allow to pass empty list of issues
Fixes #50

(GH-50) Allow to pass empty list of issues

---

README.md

Add Azure DevOps build badge

---

src/Cake.Issues.PullRequests.Tests/Cake.Issues.PullRequests.Tests.csproj
src/Cake.Issues.PullRequests/Cake.Issues.PullRequests.csproj

Build against Cake 0.33.0
Fixes #77

(GH-77) Build against Cake 0.33.0

---

src/Cake.Issues.PullRequests.Tests/Cake.Issues.PullRequests.Tests.csproj
src/Cake.Issues.PullRequests/Cake.Issues.PullRequests.csproj

Update to Cake.Issues 0.7.0-beta001
Fixes #78

(GH-78) Update to Cake.Issues 0.7.0-beta001

---

README.md
nuspec/nuget/Cake.Issues.PullRequests.nuspec

Website changed to cakeissues.net
Fixes #100

(GH-100) Change website to cakeissues.net

---

src/Cake.Issues.PullRequests.Tests/BasePullRequestSystemTests.cs
src/Cake.Issues.PullRequests.Tests/Cake.Issues.PullRequests.Tests.csproj
src/Cake.Issues.PullRequests.Tests/FakePullRequestSystem.cs
src/Cake.Issues.PullRequests.Tests/OrchestratorTests.cs
src/Cake.Issues.PullRequests/BasePullRequestSystem.cs
src/Cake.Issues.PullRequests/Cake.Issues.PullRequests.csproj
src/Cake.Issues.PullRequests/IPullRequestSystem.cs
src/Cake.Issues.PullRequests/Orchestrator.cs

Update to Cake.Issues 0.8.0
Fixes #113

(GH-113) Update to Cake.Issues 0.8.0

---

src/Cake.Issues.PullRequests/IssueFilterer.cs

Improve logging for performance of issue filtering. Duration for filter operation is now logged for every step of the filtering process.

(GH-116) Improve performance logging for issue filtering

---

src/Cake.Issues.PullRequests.Tests/IssueFiltererTests.cs
src/Cake.Issues.PullRequests.Tests/OrchestratorTests.cs

Improve tests for IssueFilterer

Improve tests for IssueFilterer

---

src/Cake.Issues.PullRequests/Orchestrator.cs

Don't log issues if no issues are posted due to outdated commit.
Fixes #136

(GH-136) Don't log issues if no issues are posted due to outdated commit

---

src/Cake.Issues.PullRequests.Tests/OrchestratorTests.cs

Add tests for edge cases

---

src/Cake.Issues.PullRequests.Tests/Cake.Issues.PullRequests.Tests.csproj
src/Cake.Issues.PullRequests.Tests/FakePullRequestSystem.cs
src/Cake.Issues.PullRequests.Tests/IssueFiltererFixture.cs
src/Cake.Issues.PullRequests.Tests/IssueFiltererTests.cs
src/Cake.Issues.PullRequests.Tests/OrchestratorForIssueProvidersFixture.cs
src/Cake.Issues.PullRequests.Tests/OrchestratorForIssuesFixture.cs
src/Cake.Issues.PullRequests.Tests/OrchestratorTests.cs
src/Cake.Issues.PullRequests/Aliases.cs
src/Cake.Issues.PullRequests/BasePullRequestSystem.cs
src/Cake.Issues.PullRequests/Cake.Issues.PullRequests.csproj
src/Cake.Issues.PullRequests/IPullRequestSystem.cs
src/Cake.Issues.PullRequests/IReportIssuesToPullRequestFromIssueProviderSettings.cs
src/Cake.Issues.PullRequests/IReportIssuesToPullRequestSettings.cs
src/Cake.Issues.PullRequests/IssueFilterer.cs
src/Cake.Issues.PullRequests/Orchestrator.cs
src/Cake.Issues.PullRequests/ReportIssuesToPullRequestFromIssueProviderSettings.cs

Update Cake.Issues to 0.9.0 Beta 2
Fixes #154

(GH-154) Update Cake.Issues to 0.9.0
